### PR TITLE
use some StringSyntax Xml

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Review by Evangelink — COMMENTED** [review]
You will probably need to enrich the polyfill file to add this new attribute.

**Comment by SimonCropp** [comment]
thanks. will take a look at that

have u considered using some pre-packaged polyfills? eg https://github.com/SimonCropp/Polyfill ?

**Comment by Evangelink** [comment]
> have u considered using some pre-packaged polyfills? eg [SimonCropp/Polyfill](https://github.com/SimonCropp/Polyfill) ?

Happy to set it up, but lets make sure it doesn't flow as dependency to our package.

**Comment by Evangelink** [comment]
Hopefully with the rebase we should be good now.

**Review by Evangelink — APPROVED** [review]

**Pull request merged**
