### PR TITLE
Add copy of pipeline for migration

### PR DESCRIPTION
**Pull request by nohwnd**
Copy of the pipeline, so we can reconfigure the PR builds to use this. Will cleanup the non-official stuff in later prs.

### CODE REVIEW

**Review by MarcoRossignoli — APPROVED** [review]

**Comment by MarcoRossignoli** [comment]
FYI @Evangelink this is first step for the migration

**Comment by Evangelink** [comment]
@nohwnd @MarcoRossignoli I'd prefer to have the opposite: `azure-pipeline-official.yml` for internal/main and `azure-pipeline.yml` for the PR. This is more aligned to what other dotnet repos are doing.

**Comment by nohwnd** [comment]
Sure, no problem.

Odesláno z aplikace Outlook pro iOS<https://aka.ms/o0ukef>
________________________________
Od: Amaury Levé ***@***.***>
Odesláno: Saturday, March 2, 2024 10:32:36 AM
Komu: microsoft/testfx ***@***.***>
Kopie: Jakub Jares ***@***.***>; Mention ***@***.***>
Předmět: Re: [microsoft/testfx] Add copy of pipeline for migration (PR #2490)


@nohwnd<https://github.com/nohwnd> @MarcoRossignoli<https://github.com/MarcoRossignoli> I'd prefer to have the opposite: azure-pipeline-official.yml for internal/main and azure-pipeline.yml for the PR. This is more aligned to what other dotnet repos are doing.

**Comment by nohwnd** [comment]
I originally did it like this to keep all the rel/* branches buildable, if there are any PRs towards them.

**Pull request merged**
