### PR TITLE
use ReadLineAsync from polyfill

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by SimonCropp** [comment]
whats the failed test?

**Review by Evangelink — CHANGES_REQUESTED** [review]
You have dropped too much code, the read is fully gone.

**Comment by SimonCropp** [comment]
@Evangelink i think it is still there ? https://github.com/microsoft/testfx/pull/3837/files#diff-09ebded200ee21d2dd09a73b0b6410a3bb42afd5a601763ac2c4290b0a829477R90

**Comment by Evangelink** [comment]
I am just blind... Sorry

**Review by Evangelink — APPROVED** [review]

**Review by Evangelink — APPROVED** [review]

**Review by Evangelink — COMMENTED** [review]
The cancellation token seems to not be working as expected. The tests are failing because of some hangs.

**Comment by Evangelink** [comment]
I can reproduce locally the hang, I'll try to have a look at what's hanging tomorrow.

**Comment by SimonCropp** [comment]
perhaps a bug in my polyfill code?

**Comment by Evangelink** [comment]
@SimonCropp I don't know if that's a bug per say but for sure your implementation only look at the token as the entry of the method:
image

while your implementation do check it during the execution.

**Review by Evangelink — CHANGES_REQUESTED** [review]
The refactoring is causing a functional difference that can lead to hangs.

**Pull request closed without merging**
