### PR TITLE
Feat: Add [STATestMethod]

### PR DESCRIPTION
**Pull request by Evangelink**
Relates to #2688

### CODE REVIEW

**Review by MarcoRossignoli — APPROVED** [review]

**Comment by MWinhard** [comment]
[STATestClass] and [STATestMethod] attributes are still not recognized. I'm using latest stable MSTest 3.5.2 and Visual Studio 2022 17.11.0. Do I need something else?

**Comment by Evangelink** [comment]
They will be included in 3.6.0, we can release a public preview version if you are interested.

**Comment by MWinhard** [comment]
Thank you for the quick reply. I can wait for 3.6.0. But please document in [https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-mstest-writing-tests-attributes](url) that `[STATestClass]` and `[STATestMethod]` are available "starting with MSTest 3.6", as with the `CooperativeCancellation` property.

**Comment by Evangelink** [comment]
@MWinhard that's valuable feedback, thank you. I am addressing it here https://github.com/dotnet/docs/pull/42330

**Pull request merged**
