### PR TITLE
WIP: Remove .txt extension from LICENSE file

### LINKED ISSUE #777: license extension rename broke links
Side effect generated by #603. Also, taking in consideration that Github support LICENSE, why add the `.txt`?
I can open an MR, but in my opinion the problem is the file extension. Waiting for feedback.

## Steps to reproduce
* Go to the License section on [README.md](https://github.com/microsoft/testfx/blob/master/README.md) and click on the _MIT license_ link

## Expected behavior
Open license content

## Actual behavior
404

### PR DESCRIPTION
**Pull request by anqre**
Closes #777 

@Haplois

### CODE REVIEW

**Comment by anqre** [comment]
@Haplois can you help me here? I can't run the build locally (macOS).

**Comment by Haplois** [comment]
Yes, I'll fix the `.nuspec` files and merge this.

**Comment by anqre** [comment]
> Yes, I'll fix the `.nuspec` files and merge this.

Thank you

**Review by Haplois — APPROVED** [review]

**Comment by Haplois** [comment]
Merged. @anqre, thank you for your contribution.

**Pull request merged**
