### PR TITLE
Updated .nuspec files with new license tag

### LINKED ISSUE #601: <licenseUrl> tag deprecating soon, specify license in the package directly
## Description
Uploading nuget apckages giving following warning : 
image

### PR DESCRIPTION
**Pull request by parrainc**
Fixes #601

### CODE REVIEW

**Comment by jayaranigarg** [comment]
@parrainc : Build is failing with error 'Cannot find file License.txt'.
Few changes that needs to be done:
1. Rename the [License ](https://github.com/Microsoft/testfx/blob/master/LICENSE)file to License.txt
2. Make changes in the build [script](https://github.com/Microsoft/testfx/blob/master/scripts/Build.ps1#L260) to make sure this license file is dropped to staging directory i.e. something like 
```
	#Copy over license file to staging directory
	$licenseFilePath = Join-Path $env:TF_ROOT_DIR "LICENSE.txt"
	Copy-Item $licenseFilePath $stagingDir -Force
```

**Comment by parrainc** [comment]
Done. License file was renamed as part of first commit, what i missed was updating the build script to copy the file over staging dir.

**Comment by parrainc** [comment]
@jayaranigarg just noticed the azure pipelines (TestFc.PR) check throw a few warnings and failed with a unit test project due to same warning: "_The package signature file entry is invalid. The central directory header field 'compression method' has an invalid value (8)_"

I'm not sure if this have something to do with the nuget version that is being pulled in, but it would help updating the "Pull in NuGet" task given that the minimum version where this nuspec changes are supported is v4.9.2 and the pipeline is pulling v4.5.1.

**Comment by jayaranigarg** [comment]
>I'm not sure if this have something to do with the nuget version that is being pulled in, but it would help updating the **"Pull in NuGet"** task given that the minimum version where this nuspec changes are supported is v4.9.2 and the pipeline is pulling v4.5.1.

@parrainc : In this case, consider changing [azure-pipelines.yml](https://github.com/Microsoft/testfx/blob/master/azure-pipelines.yml#L16) file to pull in 4.9.2 version.

**Comment by jayaranigarg** [comment]
@parrainc : The build is failing for NetCore PlatformService. This seems to be like a known [issue ](https://github.com/NuGet/Home/issues/7414#issuecomment-472561481).
The above thread should help to unblock the PR.

**Comment by parrainc** [comment]
oh, good to hear (the known issue part). I'm fixing it right away and push it up again.

**Comment by jayaranigarg** [comment]
@parrainc : Awesome 🎉 Thank you for your contribution!! Will go ahead and merge the PR.

**Pull request merged**
