### PR TITLE
Create WithNoNamespaceTests.cs

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by Evangelink** [comment]
Hi @SimonCropp! Thanks for the contribution. May I ask for some context? Are you trying to reproduce a bug?

**Comment by Evangelink** [comment]
We are having some issues with CI today :c I will ping you once this is fixed.

Regarding local build. Are you doing `.\Build.cmd -Full`? The only problem I am aware of is about Windows SDK (required for UWP) that you could install through the following script https://github.com/microsoft/testfx/blob/main/scripts/Install-WindowsSDK.ps1. If you are facing any other issue, would you mind opening an issue with some details and I will take care of it.

**Comment by SimonCropp** [comment]
```
PS D:\Code\testfx> .\Build.cmd -Full
... Perform-Restore: Started.
D:\Code\testfx\scripts\build.ps1 : The term 'D:\Code\testfx\packages\vswhere\2.5.2\tools\vswhere.exe' is not
recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if
a path was included, verify that the path is correct and try again.
At line:1 char:1
+ D:\Code\testfx\scripts\build.ps1 -Full; exit $LastExitCode;
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\Code\testfx\...ols\vswhere.exe:String) [build.ps1], CommandNotFound
   Exception
    + FullyQualifiedErrorId : CommandNotFoundException,build.ps1

```

**Comment by nohwnd** [comment]
@SimonCropp In vstest, I saw that antivirus (or maybe something else) regularly removed some exes from our nuget cache, leaving the contents corrupted. 

Please try deleting the whole packages/vswhere folder and try again. 

This is what we need to do in vstest to make it stable, but I did not see it happen with vswhere, but we are of course using different environments than you do.

https://github.com/microsoft/vstest/blob/main/scripts/build.ps1#L122-L135

**Comment by Evangelink** [comment]
@SimonCropp sorry the pipeline issue took a long time to be fixed. Your PR is now green.

**Comment by SimonCropp** [comment]
@Evangelink but how? no namespaces fails when i run mstest locally

**Comment by Evangelink** [comment]
I will try to build your PR locally and see what's happening (I am quite busy till mid afternoon).

**Comment by SimonCropp** [comment]
@Evangelink no rush. and i am speaking in the context of running a test from the consumer context. not within the testfx codebase

**Comment by Evangelink** [comment]
I have create a new test project and I can reproduce your issue. Up to `2.2.3` tests are discovered and after they are not.

**Comment by Evangelink** [comment]
No need to run @Haplois

**Comment by Evangelink** [comment]
Closing this PR, we will handle the bug from the ticket.

**Comment by SimonCropp** [comment]
@Evangelink note i was going to attempt a pr since the issue has been open for over a year.

**Comment by Evangelink** [comment]
Oh sweet! I am taking over the repo and I am looking at open bugs with the idea to fix as many as possible in `2.3.0` (we will try to backport in a `2.2.11` but some of the old code design/split makes it hard to work with).

I'd be happy to help you fixing the issue if you are still interested in helping!

**Comment by SimonCropp** [comment]
still interested. but ATM i am stumped as to why my pr didnt break the build

**Comment by Evangelink** [comment]
I will see what's going-on and try to have a failing test for you to start working.

**Comment by Evangelink** [comment]
It's interesting, as far as I can tell, the test is ignored as it doesn't contain any namespace so CI is not failing. We will need to create some E2E test and check the output to ensure a test was indeed run. I will try to provide an example.

**Comment by Haplois** [comment]
So, there is a bug in [microsoft/vstest](https://github.org/microsoft/vstest) - 

We call a VSTest api to get details of a `TestMethod`.

https://github.com/microsoft/testfx/blob/ee68fd68345f1e773b7a1a8f9f25b26350cfaba7/src/Adapter/MSTest.TestAdapter/ObjectModel/TestMethod.cs#L66-L71

`managedType` is usually "`Namespace.ClassName`" and when there isn't any namespace what we expect is just `ClassName`. Instead we get `.ClassName`. Which causes all kinds of hell. We will patch VSTest, and TestFx.

**Pull request closed without merging**
