### PR TITLE
Add known report files

### PR DESCRIPTION
**Pull request by nohwnd**
Add extensions for report files used by xunit.

image

### CODE REVIEW

**Review by Evangelink — APPROVED** [review]

**Comment by Evangelink** [comment]
Issues on native AOT tests, I'll force merge this PR and work on fixing the tests this afternoon (flakiness).

**Comment by bradwilson** [comment]
FYI I changed the default xunit report extension from `.xml` to `.xunit` for parity with the others.

**Comment by bradwilson** [comment]
Though I do think people, when they override filenames, will very commonly use `.xml` (and maybe `.json` for the CTRF), so leaving `.xml` in the list seems like a good idea.

**Comment by nohwnd** [comment]
Ok then I should add .xunit as well.

**Pull request merged**
