### PR TITLE
remove redundant variables in ConstructorShouldPopulateSettings

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by Evangelink** [comment]
@SimonCropp you will need to remove line 57:

```
test\UnitTests\MSTestAdapter.UnitTests\Execution\UnitTestRunnerTests.cs(57,16): error CS0219: (NETCORE_ENGINEERING_TELEMETRY=Build) The variable 'runSettingsXml' is assigned but its value is never used
```

**Comment by SimonCropp** [comment]
@Evangelink done

**Review by Evangelink — APPROVED** [review]

**Comment by Evangelink** [comment]
Some tests are failing:

```text
Error during test: System.Exception: Verification failed for MSTestSettings.CurrentSettings.ForcedLegacyMode at line 66 of method 'ConstructorShouldPopulateSettings' in file '/_/test/UnitTests/MSTestAdapter.UnitTests/Execution/UnitTestRunnerTests.cs'.
   at TestFramework.ForTestingMSTest.TestContainer.Throw(String expression, String caller, String filePath, Int32 lineNumber) in /_/test/Utilities/TestFramework.ForTestingMSTest/TestContainer.cs:line 97
   at TestFramework.ForTestingMSTest.TestContainer.Verify(Boolean condition, String expression, String caller, String filePath, Int32 lineNumber) in /_/test/Utilities/TestFramework.ForTestingMSTest/TestContainer.cs:line 62
```

```text
  Failed Microsoft.VisualStudio.TestPlatform.MSTestAdapter.UnitTests.Execution.UnitTestRunnerTests.ConstructorShouldPopulateSettings
  Error Message:
   Error during test: Verification failed for MSTestSettings.CurrentSettings.ForcedLegacyMode at line 66 of method 'ConstructorShouldPopulateSettings' in file '/_/test/UnitTests/MSTestAdapter.UnitTests/Execution/UnitTestRunnerTests.cs'.
  Stack Trace:
     at TestFramework.ForTestingMSTest.TestContainer.Throw(String expression, String caller, String filePath, Int32 lineNumber) in /_/test/Utilities/TestFramework.ForTestingMSTest/TestContainer.cs:line 97
   at TestFramework.ForTestingMSTest.TestContainer.Verify(Boolean condition, String expression, String caller, String filePath, Int32 lineNumber) in /_/test/Utilities/TestFramework.ForTestingMSTest/TestContainer.cs:line 62
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.UnitTests.Execution.UnitTestRunnerTests.ConstructorShouldPopulateSettings() in /_/test/UnitTests/MSTestAdapter.UnitTests/Execution/UnitTestRunnerTests.cs:line 66
```

**Comment by SimonCropp** [comment]
i assume the tests are relying on some state change done by the UnitTestRunner constructor. so will close this

**Pull request closed without merging**
