### PR TITLE
use EnumPolyfill.Parse

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by SimonCropp** [comment]
@Evangelink u will need to unlock the use of the new version of polyfill. i am not sure how that process works

**Comment by Evangelink** [comment]
@SimonCropp Doing that right now.

**Review by Evangelink — APPROVED** [review]

**Comment by SimonCropp** [comment]
can we get the build failure to include the test output?

**Comment by Evangelink** [comment]
All good, we just need the rebase here, I broke main earlier without noticing. Sorry!

**Pull request merged**
