### PR TITLE
Fix SelfRegisteredExtensions type to be internal

### LINKED ISSUE #3813: Build error when one test project references another
## Describe the bug

Starting with MSTest 3.6.0, when one test project references another test project, warning CS0436 is emitted by the compiler because the same type is being compiled into two assemblies.

## Steps To Reproduce

1. Pull [`build-error-on-reference` branch](https://github.com/bdukes/mstest-demo/tree/build-error-on-reference) from [bdukes/mstest-demo](https://github.com/bdukes/mstest-demo)
2. `dotnet build`

## Expected behavior

The build command is successful.

## Actual behavior

The build command fails with the following error:

```
I:\code\MSTestDemo\ProjectTwo.Tests\obj\Debug\net8.0\TestPlatformEntryPoint.cs(13,9): warning CS0436: The type 'SelfRegi
steredExtensions' in 'I:\code\MSTestDemo\ProjectTwo.Tests\obj\Debug\net8.0\AutoRegisteredExtensions.cs' conflicts with t
he imported type 'SelfRegisteredExtensions' in 'ProjectOne.Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
. Using the type defined in 'I:\code\MSTestDemo\ProjectTwo.Tests\obj\Debug\net8.0\AutoRegisteredExtensions.cs'. [I:\code
\MSTestDemo\ProjectTwo.Tests\ProjectTwo.Tests.csproj]
```

### PR DESCRIPTION
**Pull request by Evangelink**
Fixes #3813

I'll work on adding some acceptance test as a follow-up but I have manually tested against the demo project in the linked issue.

### CODE REVIEW

**Comment by MarcoRossignoli** [comment]
@bradwilson we need to internalize the service registration helper, as soon as this PR is merged can you give it a try with the nightly feed and let us know if it's breaking something on your side?

**Review by MarcoRossignoli — APPROVED** [review]

**Comment by bradwilson** [comment]
@MarcoRossignoli What package version is this fixed in? I don't see it yet in `1.5.0-preview.24480.6`.

**Comment by bradwilson** [comment]
`1.5.0-preview.24480.9` just popped up and it's in there, guess I wasn't patient enough. 😂 

No issues on my side. https://github.com/xunit/xunit/compare/main...testfx-3891

**Comment by Evangelink** [comment]
Thank you @bradwilson

**Pull request merged**
