### PR TITLE
Fix fsharp error when net5.0 SDK is on the system

### PR DESCRIPTION
**Pull request by nohwnd**

### CODE REVIEW

**Review by Haplois — APPROVED** [review]

**Review by Haplois — CHANGES_REQUESTED** [review]
support for `net451` is removed from fsharp. I updated this test to target `net472`, and problem went away. The fix has already merged into master. 

Do you think this PR is still required?

**Comment by nohwnd** [comment]
> and problem went away. 

Can you confirm it still run those f# tests?

**Comment by Haplois** [comment]
Yes, I can confirm that [this][1] pipeline run the tests successfully after version update. 

   [1]: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4197926&view=results

**Comment by nohwnd** [comment]
abandoning.

**Pull request closed without merging**
