### PR TITLE
Added missing library to the NuGet package.

### LINKED ISSUE #789: Cannot run tests anymore after upgrading to 2.2.1
Attempt to upgrade our test projects to version from 2.1.2 to 2.2.1 results in the following test execution error:

`An exception occurred while invoking executor 'executor://mstestadapter/v2': Could not load file or assembly 'Microsoft.TestPlatform.AdapterUtilities, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.`

[AB#1287803](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1287803)

### PR DESCRIPTION
**Pull request by Haplois**
Fixes #789

### CODE REVIEW

**Review by cvpoienaru — APPROVED** [review]
LGTM

**Comment by avivanoff** [comment]
@Haplois, when do you expect to have updated NuGet package?

**Comment by Haplois** [comment]
@avivanoff, after PR merges, a package is published into our daily feed; specifically for this PR, version 2.2.3 is just published. It might take 5-10 minutes to appear, though.

**Comment by avivanoff** [comment]
@Haplois, looks much better.

**Pull request merged**
