### PR TITLE
Revert adding net7.0 and net8.0 to packages

### PR DESCRIPTION
**Pull request by Evangelink**
Relates to https://github.com/microsoft/testfx/pull/1917#issuecomment-1871211763

### CODE REVIEW

**Comment by MarcoRossignoli** [comment]
why? As soon as we add new analyzers to improve or use new api we will start to benefit from the multi-tfm. What's the issue to have multi-tfm?

**Review by MarcoRossignoli — CHANGES_REQUESTED** [review]
I don't see problem with multi-tfm here if not the size.

**Comment by Evangelink** [comment]
@Romfos the runner `Microsoft.Testing.Platform` is actually having improved APIs for both net7.0 and net8.0 so it's providing quite some perf boost to have the extra additions. We could avoid the extra TFMs for the framework only but it's going to be easier to know this is already packaging everything needed so we can start using the new features.

**Comment by Romfos** [comment]
it make sense if we have specific optimizations for .net 8.0. thank you for clarification

**Comment by Evangelink** [comment]
Thanks for caring :)

**Pull request closed without merging**
