### PR TITLE
Loc 20190607 master

### PR DESCRIPTION
**Pull request by v-zbsail**

### CODE REVIEW

**Comment by jayaranigarg** [comment]
@v-zbsail : This too is having merge conflicts.

**Comment by v-zbsail** [comment]
@jayaranigarg  Yes, because the files would have to go trough the whole localization process in order to have you last changes in our files. It will be propagated to our files and localized in next cycle.

**Comment by jayaranigarg** [comment]
v-zbsail : I understand. But we can't merge the PR in this state with conflicts. Please re-trigger the localization process and raise the PR once it has all those changes.

**Comment by v-zbsail** [comment]
@jayaranigarg Ok, we are working on it. Just want to mention, that at this point the affected resource will not be localized as it would take more time to run it by translators. But we will get rid of the conflict.

**Comment by v-zbsail** [comment]
@jayaranigarg I've just commited the updated files. This should fix the merge conflict.

**Comment by jayaranigarg** [comment]
@v-zbsail : Apologies I missed this. It is still showing conflicts.

**Comment by v-zbsail** [comment]
We will created a new PR with the latest files.
Closing this one as it's obsolete.

**Pull request closed without merging**
