### PR TITLE
remove usages of DefinedTypes

### PR DESCRIPTION
**Pull request by SimonCropp**
DefinedTypes is essentially an inefficient wrapper around GetTypes().
```
   public virtual IEnumerable<TypeInfo> DefinedTypes
        {
            [RequiresUnreferencedCode("Types might be removed")]
            get
            {
                Type[] types = GetTypes();
                TypeInfo[] typeinfos = new TypeInfo[types.Length];
                for (int i = 0; i < types.Length; i++)
                {
                    TypeInfo typeinfo = types[i].GetTypeInfo();
                    if (typeinfo == null)
                        throw new NotSupportedException(SR.Format(SR.NotSupported_NoTypeInfo, types[i].FullName));

                    typeinfos[i] = typeinfo;
                }
                return typeinfos;
            }
        }
```

better to just use GetTypes() directly and not bother messing with TypeInfo

### CODE REVIEW

**Comment by Evangelink** [comment]
The PR is now touching more files than expected but I was getting a lot of IDE warnings popping (not sure why now).

**Comment by SimonCropp** [comment]
@Evangelink  shall we close, and i till try for some more narrowly targeted PRs?

**Comment by Evangelink** [comment]
Linux errors are just a missing rebase, I broke main without noticing. It's fixed now.

For windows, and I can repro locally, it seems that the tests are getting stuck. Not sure why we don't end up with the dumps created (cc @MarcoRossignoli)

**Comment by Evangelink** [comment]
Rebasing, I have managed to run all tests locally so it should be green in CI now.

**Comment by Evangelink** [comment]
Closing this one.

**Pull request closed without merging**
