### PR TITLE
Enable TestContext.AddResultFile API for WinUI

### PR DESCRIPTION
**Pull request by engyebrahim**
fix: https://github.com/microsoft/testfx/issues/727 and https://github.com/microsoft/testfx/issues/1594

### CODE REVIEW

**Comment by engyebrahim** [comment]
Hi @MSLukeWest, Can you please check the change using UWP?

**Review by MSLukeWest — APPROVED** [review]
Please make sure to let me know when this gets inserted into VS so I can do some additional testing.

**Review by MSLukeWest — APPROVED** [review]

**Comment by Evangelink** [comment]
Ping @engyebrahim

**Review by Evangelink — APPROVED** [review]
As per my tests this seems to be working only for WinUI. I suspect that UWP provider is ignoring this info we are providing.

Please double check if you see the same behaviour. Approving now so you can merge when you are done with testing.

**Pull request merged**
