### PR TITLE
Update description for (init/cleanup) analyzers

### PR DESCRIPTION
**Pull request by engyebrahim**
fix: https://github.com/microsoft/testfx/issues/3323

### CODE REVIEW

**Review by Evangelink — COMMENTED** [review]
This is still incomplete. Maybe the best is to copy what appears on the doc page (e.g. https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0012)

**Comment by engyebrahim** [comment]
@Evangelink https://github.com/microsoft/testfx/blob/main/src/Analyzers/MSTest.Analyzers/Helpers/FixtureUtils.cs#L50
the code is different for int/cleanup assembly

**Review by Evangelink — DISMISSED** [review]
Small nit, could you have keywords and types surrounded by single quotes please. Otherwise LGTM

**Review by Evangelink — APPROVED** [review]
Thanks @engyebrahim!

**Pull request merged**
