### PR TITLE
Increment Console Test Counts with a lock to prevent read/write race conditions

### PR DESCRIPTION
**Pull request by thomhurst**
Should help (and maybe fix) #3088

### CODE REVIEW

**Review by nohwnd — APPROVED** [review]

**Comment by nohwnd** [comment]
The RunTests_With_VSTest breakage is not your fault @thomhurst

**Comment by nohwnd** [comment]
were you able to confirm this change fixes the problem?

You are probably familiar with this but I will spell it out anyway: 

If you do `./build.cmd -pack ` you will get your packages locally, and then you can use them in your project. 

You'd need nuget.config to grab packages from local source that you can setup like this:
https://aka.ms/mstest/preview

Just replace the online path with path to your package folder: e.g. S:\p\testfx2\artifacts\packages\Debug\Shipping

**Comment by thomhurst** [comment]
> ./build.cmd -pack

Are you able to build for me and chuck the nupkg files here? That build script doesn't work for me.

First run:
```
PS C:\git\other\testfx> ./build.cmd -pack
Downloading Windows SDK 10.0.16299...
Installing Windows SDK, if setup requests elevation please approve.
Installation succeeded
GET https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.ps1
  Attempting to install 'sdk v8.0.101' from public location.
dotnet-install: Remote file https://dotnetcli.azureedge.net/dotnet/Sdk/8.0.101/dotnet-sdk-8.0.101-win-x64.zip size is 282520038 bytes.
dotnet-install: Downloaded file https://dotnetcli.azureedge.net/dotnet/Sdk/8.0.101/dotnet-sdk-8.0.101-win-x64.zip size is 282520038 bytes.
dotnet-install: The remote and local file sizes are equal.
dotnet-install: Extracting the archive.
dotnet-install: Adding to current process PATH: "C:\git\other\testfx\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: Note that the script does not resolve dependencies during installation.
dotnet-install: To check the list of dependencies, go to https://learn.microsoft.com/dotnet/core/install/windows#dependencies
dotnet-install: Installed version is 8.0.101
dotnet-install: Installation finished
Downloading vswhere
Downloading RoslynTools.MSBuild 17.8.0
{"$id":"1","innerException":null,"message":"Cannot find the file RoslynTools.MSBuild.17.8.0.nupkg in package 'RoslynTools.MSBuild 17.8.0' in feed 'dotnet-eng'","typeName":"Microsoft.VisualStudio.Services.Packaging.Shared.WebApi.Exceptions.PackageNotFoundException, Microsoft.VisualStudio.Services.Packaging.Shared.WebApi","typeKey":"PackageNotFoundException","errorCode":0,"eventId":3000}
Retrying. Waiting for 3 seconds before next attempt (2 of 5).
{"$id":"1","innerException":null,"message":"Cannot find the file RoslynTools.MSBuild.17.8.0.nupkg in package 'RoslynTools.MSBuild 17.8.0' in feed 'dotnet-eng'","typeName":"Microsoft.VisualStudio.Services.Packaging.Shared.WebApi.Exceptions.PackageNotFoundException, Microsoft.VisualStudio.Services.Packaging.Shared.WebApi","typeKey":"PackageNotFoundException","errorCode":0,"eventId":3000}
Retrying. Waiting for 7 seconds before next attempt (3 of 5).
{"$id":"1","innerException":null,"message":"Cannot find the file RoslynTools.MSBuild.17.8.0.nupkg in package 'RoslynTools.MSBuild 17.8.0' in feed 'dotnet-eng'","typeName":"Microsoft.VisualStudio.Services.Packaging.Shared.WebApi.Exceptions.PackageNotFoundException, Microsoft.VisualStudio.Services.Packaging.Shared.WebApi","typeKey":"PackageNotFoundException","errorCode":0,"eventId":3000}
Retrying. Waiting for 15 seconds before next attempt (4 of 5).
{"$id":"1","innerException":null,"message":"Cannot find the file RoslynTools.MSBuild.17.8.0.nupkg in package 'RoslynTools.MSBuild 17.8.0' in feed 'dotnet-eng'","typeName":"Microsoft.VisualStudio.Services.Packaging.Shared.WebApi.Exceptions.PackageNotFoundException, Microsoft.VisualStudio.Services.Packaging.Shared.WebApi","typeKey":"PackageNotFoundException","errorCode":0,"eventId":3000}
Retrying. Waiting for 31 seconds before next attempt (5 of 5).
{"$id":"1","innerException":null,"message":"Cannot find the file RoslynTools.MSBuild.17.8.0.nupkg in package 'RoslynTools.MSBuild 17.8.0' in feed 'dotnet-eng'","typeName":"Microsoft.VisualStudio.Services.Packaging.Shared.WebApi.Exceptions.PackageNotFoundException, Microsoft.VisualStudio.Services.Packaging.Shared.WebApi","typeKey":"PackageNotFoundException","errorCode":0,"eventId":3000}
Unable to download file in 5 attempts.
Exception calling "ExtractToDirectory" with "2" argument(s): "Could not find file 'C:\git\other\testfx\.tools\msbuild\17.8.0\RoslynTools.MSBuild.17.8.0.nupkg'."
PS C:\git\other\testfx> ./build.cmd -pack
Windows SDK 10.0.16299 is already installed, skipping...
at Exec-Process, C:\git\other\testfx\eng\common\tools.ps1: line 89
at MSBuild-Core, C:\git\other\testfx\eng\common\tools.ps1: line 840
at InitializeToolset, C:\git\other\testfx\eng\common\tools.ps1: line 715
at Build, C:\git\other\testfx\eng\common\Build.ps1: line 93
at <ScriptBlock>, C:\git\other\testfx\eng\common\Build.ps1: line 158
at <ScriptBlock>, C:\git\other\testfx\eng\build.ps1: line 70
at <ScriptBlock>, <No file>: line 1
Exception calling "Start" with "0" argument(s): "The system cannot find the file specified"
```

Any run after:
```
PS C:\git\other\testfx> ./build.cmd -pack
Windows SDK 10.0.16299 is already installed, skipping...
at Exec-Process, C:\git\other\testfx\eng\common\tools.ps1: line 89
at MSBuild-Core, C:\git\other\testfx\eng\common\tools.ps1: line 840
at InitializeToolset, C:\git\other\testfx\eng\common\tools.ps1: line 715
at Build, C:\git\other\testfx\eng\common\Build.ps1: line 93
at <ScriptBlock>, C:\git\other\testfx\eng\common\Build.ps1: line 158
at <ScriptBlock>, C:\git\other\testfx\eng\build.ps1: line 70
at <ScriptBlock>, <No file>: line 1
Exception calling "Start" with "0" argument(s): "The system cannot find the file specified"
```

**Comment by Evangelink** [comment]
@MarcoRossignoli please review too.

@thomhurst the build is working for me, I would need to try on my personal laptop (will do later) to check if something is broken for non-MS users.

**Comment by thomhurst** [comment]
@Evangelink if the build is working for you could you chuck me the nupkg files?

**Comment by MarcoRossignoli** [comment]
The consume is guarantee to be thread safe, it's implemented using a queue, so I don't think that the issue is race condition. 
We have also a test for it https://github.com/microsoft/testfx/blob/main/test/UnitTests/Microsoft.Testing.Platform.UnitTests/Messages/AsynchronousMessageBusTests.cs#L102

So or there's a bug in message bus or another possibilities is that the "adapter" doesn't await always when publish inside the message bus before to complete the request. I'll try with a dummy adapter.

**Comment by MarcoRossignoli** [comment]
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Testing.Platform" Version="1.2.1" />
  </ItemGroup>
</Project>
```
```cs
using Microsoft.Testing.Platform.Capabilities.TestFramework;
using Microsoft.Testing.Platform.Capabilities;
using Microsoft.Testing.Platform.Extensions.Messages;
using Microsoft.Testing.Platform.Extensions.TestFramework;
using Microsoft.Testing.Platform.Builder;

var builder = await TestApplication.CreateBuilderAsync(args);
builder.RegisterTestFramework(_ => new Capabilities(), (_, __) => new DummyAdapter());
using var app = await builder.BuildAsync();
return await app.RunAsync();

internal class DummyAdapter : ITestFramework, IDataProducer
{
    private Random random = new Random();

    public string Uid => nameof(DummyAdapter);

    public string Version => string.Empty;

    public string DisplayName => string.Empty;

    public string Description => string.Empty;

    public Type[] DataTypesProduced => new[] { typeof(TestNodeUpdateMessage) };

    public Task<CloseTestSessionResult> CloseTestSessionAsync(CloseTestSessionContext context) => Task.FromResult(new CloseTestSessionResult() { IsSuccess = true });

    public Task<CreateTestSessionResult> CreateTestSessionAsync(CreateTestSessionContext context) => Task.FromResult(new CreateTestSessionResult() { IsSuccess = true });

    public Task ExecuteRequestAsync(ExecuteRequestContext context)
    {
        _ = Task.Run(() =>
        {
            try
            {
                ParallelLoopResult result = Parallel.For(0, 100, async i =>
                {
                    Thread.Sleep(random.Next(50, 150));
                    await context.MessageBus.PublishAsync(this, new TestNodeUpdateMessage(context.Request.Session.SessionUid,
                        new TestNode() { Uid = Guid.NewGuid().ToString(), DisplayName = "Test", Properties = new(PassedTestNodeStateProperty.CachedInstance) }));
                });

                while (!result.IsCompleted) ;
            }
            finally
            {
                context.Complete();
            }

        });

        return Task.CompletedTask;
    }

    public Task<bool> IsEnabledAsync() => Task.FromResult(true);
}

internal class Capabilities : ITestFrameworkCapabilities
{
    IReadOnlyCollection<ITestFrameworkCapability> ICapabilities<ITestFrameworkCapability>.Capabilities
        => Array.Empty<ITestFrameworkCapability>();
}
```

@thomhurst here a sample where I get always 100 tests run at the end running in parallel.

**Comment by thomhurst** [comment]
> ```
> <Project Sdk="Microsoft.NET.Sdk">
>   <PropertyGroup>
>     <OutputType>Exe</OutputType>
>     <TargetFramework>net9.0</TargetFramework>
>     <ImplicitUsings>enable</ImplicitUsings>
>     <Nullable>enable</Nullable>
>   </PropertyGroup>
>   <ItemGroup>
>     <PackageReference Include="Microsoft.Testing.Platform" Version="1.2.1" />
>   </ItemGroup>
> </Project>
> ```
> 
> ```cs
> using Microsoft.Testing.Platform.Capabilities.TestFramework;
> using Microsoft.Testing.Platform.Capabilities;
> using Microsoft.Testing.Platform.Extensions.Messages;
> using Microsoft.Testing.Platform.Extensions.TestFramework;
> using Microsoft.Testing.Platform.Builder;
> 
> var builder = await TestApplication.CreateBuilderAsync(args);
> builder.RegisterTestFramework(_ => new Capabilities(), (_, __) => new DummyAdapter());
> using var app = await builder.BuildAsync();
> return await app.RunAsync();
> 
> internal class DummyAdapter : ITestFramework, IDataProducer
> {
>     private Random random = new Random();
> 
>     public string Uid => nameof(DummyAdapter);
> 
>     public string Version => string.Empty;
> 
>     public string DisplayName => string.Empty;
> 
>     public string Description => string.Empty;
> 
>     public Type[] DataTypesProduced => new[] { typeof(TestNodeUpdateMessage) };
> 
>     public Task<CloseTestSessionResult> CloseTestSessionAsync(CloseTestSessionContext context) => Task.FromResult(new CloseTestSessionResult() { IsSuccess = true });
> 
>     public Task<CreateTestSessionResult> CreateTestSessionAsync(CreateTestSessionContext context) => Task.FromResult(new CreateTestSessionResult() { IsSuccess = true });
> 
>     public Task ExecuteRequestAsync(ExecuteRequestContext context)
>     {
>         _ = Task.Run(async () =>
>         {
>             try
>             {
>                 List<Task> tasks = [];
>                 for (int i = 0; i < 100; i++)
>                 {
>                     tasks.Add(Task.Run(async () =>
>                     {
>                         Thread.Sleep(random.Next(100, 250));
>                         await context.MessageBus.PublishAsync(this, new TestNodeUpdateMessage(context.Request.Session.SessionUid,
>                             new TestNode() { Uid = Guid.NewGuid().ToString(), DisplayName = "Test", Properties = new(PassedTestNodeStateProperty.CachedInstance) }));
>                     }));
> 
>                     tasks.Add(Task.Run(async () =>
>                     {
>                         Thread.Sleep(random.Next(100, 250));
>                         await context.MessageBus.PublishAsync(this, new TestNodeUpdateMessage(context.Request.Session.SessionUid,
>                             new TestNode() { Uid = Guid.NewGuid().ToString(), DisplayName = "Test", Properties = new(new FailedTestNodeStateProperty("Error")) }));
>                     }));
> 
>                     tasks.Add(Task.Run(async () =>
>                     {
>                         await context.MessageBus.PublishAsync(this, new TestNodeUpdateMessage(context.Request.Session.SessionUid,
>                             new TestNode() { Uid = Guid.NewGuid().ToString(), DisplayName = "Test", Properties = new(SkippedTestNodeStateProperty.CachedInstance) }));
>                         Thread.Sleep(random.Next(100, 250));
>                     }));
>                 }
> 
>                 await Task.WhenAll(tasks);
>             }
>             finally
>             {
>                 context.Complete();
>             }
> 
>         });
> 
>         return Task.CompletedTask;
>     }
> 
>     public Task<bool> IsEnabledAsync() => Task.FromResult(true);
> }
> 
> internal class Capabilities : ITestFrameworkCapabilities
> {
>     IReadOnlyCollection<ITestFrameworkCapability> ICapabilities<ITestFrameworkCapability>.Capabilities
>         => Array.Empty<ITestFrameworkCapability>();
> }
> ```
> 
> @thomhurst here a sample where I get always 300 tests run at the end running in parallel. `Failed! - Failed: 100, Passed: 100, Skipped: 100, Total: 300, Duration: 3s 489ms - dummyadapter.dll (win-x64 - .NET 9.0.0-preview.3.24172.9)` There's a remarks in the final section here https://github.com/microsoft/testfx/blob/main/docs/testingplatform/imessagebus.md
> 
> Can you show my how do you process your tests? Are you sure that you complete the request after await all the publish?

Weird! Maybe I'm doing something wrong in my code then. But I'm confident I'm awaiting them all:

image

I'll have to have a dig around.

**Comment by MarcoRossignoli** [comment]
> Weird! Maybe I'm doing something wrong in my code then. But I'm confident I'm awaiting them all. They wouldn't appear properly in the diag files otherwise would they?

Sorry I haven't been precise enough, what I meant is that you have to be 100% that all the await are "returned" before to call the complete or otherwise the payload could not be fully enqueued, for instance the code below is bugged:

```cs
...
try
{
      _ = Task.Run(async () =>
      {
          await context.MessageBus.PublishAsync(this, new TestNodeUpdateMessage(context.Request.Session.SessionUid,
              new TestNode() { Uid = Guid.NewGuid().ToString(), DisplayName = "Test", Properties = new(PassedTestNodeStateProperty.CachedInstance) }));
      })
}
finally
{
      context.Complete();
}
...
```
Because the `context.Complete();` notifies the platform to go on that everything is done and all payload are enqueued, but like in the code above you don't know actually if you don't wait the return of the dangling task.
In the case above you could see the log because you reach the logging part inside the `PublishAsync` but it's possible that you don't "enqueue" the payload to all the "consumers" registered, guaranteed only once the await return, but it it return after the `context.Complete();` it could be too late and the consumer(for instance the console extension that's using the IDataConsumer extensibility) could not receive the payload to process in-time.

**Comment by thomhurst** [comment]
> > Weird! Maybe I'm doing something wrong in my code then. But I'm confident I'm awaiting them all. They wouldn't appear properly in the diag files otherwise would they?
> 
> Sorry I haven't been precise enough, what I meant is that you have to be 100% that all the await are "returned" before to call the complete or otherwise the payload could not be fully enqueued, for instance the code below is bugged:
> 
> ```cs
> ...
> try
> {
>       // Bug: we publish and await correctly but we don't guarantee that it will "return" the await before we call the context.Complete();
>       _ = Task.Run(async () =>
>       {
>           await context.MessageBus.PublishAsync(this, new TestNodeUpdateMessage(context.Request.Session.SessionUid,
>               new TestNode() { Uid = Guid.NewGuid().ToString(), DisplayName = "Test", Properties = new(PassedTestNodeStateProperty.CachedInstance) }));
>       })
> }
> finally
> {
>       // Complete MUST be called when all the `await context.MessageBus.PublishAsync` are "returned"
>       context.Complete();
> }
> ...
> ```
> 
> Because the `context.Complete();` notifies the platform to go on that everything is done and all payload are enqueued, but like in the code above you don't know actually if you don't wait the return of the dangling task. In the case above you could see the log because you reach the logging part inside the `PublishAsync` but it's possible that you don't "enqueue" the payload to all the "consumers" registered, guaranteed only once the await return, but it returns after the `context.Complete();` it could be too late and the consumer(for instance the console extension that's using the `IDataConsumer` extensibility) could not receive the payload to process in-time.
> 
> If you can create a repro with your code I can take a look and verify if that's the case or there's different issue.

Yeah I understand. I'm pretty sure I'm awaiting everything, but I'll have to sift through things to double check. I've got all my code on GitHub but it's not a simple repro, it'd involve sifting through my framework which I don't expect you to do. I can look at seeing if I can make a simple repro but it might not be any time soon (and may not get possible if it's an issue with my code!)

**Review by Evangelink — CHANGES_REQUESTED** [review]
Rejecting for now while we investigate the issue.

@MarcoRossignoli it could be good for us to log/fail when we receive events after receiving a complete call.

**Comment by MarcoRossignoli** [comment]
> @MarcoRossignoli it could be good for us to log/fail when we receive events after receiving a complete call.

I need to check what we can do...but it's possible that we won't catch this issue in some scenario, we cannot control the threading so if a thread is suspended before our check and the app close we could miss it, plus we share the same messagebus for the whole application and we pass in the request context. We can try to wrap it and do some check there and if the user is using it correctly we could "see something" but again depends on the usage.

**Comment by thomhurst** [comment]
Could this have caused it? Injecting in and using the IMessageBus from the service providers, rather than directly off the context object.

I was doing that, and changed my calls to use the context object, and it's all started working now.

The weird thing I don't understand though is I debugged afterwards, got the MessageBus both ways, and it said they were equal references, so if that's the case I don't understand why it's made a difference 🤯

**Comment by MarcoRossignoli** [comment]
> The weird thing I don't understand though is I debugged afterwards, got the MessageBus both ways, and it said they were equal references, so if that's the case I don't understand why it's made a difference 🤯

The instance "today" is the same but it's an "implementation" detail not exposed, the idea is that users should "flow" the context around and use that message bus, close to the "complete". The request doesn't have the `IServiceProvider` because is "not needed" to fulfil a request, only push info to the `IMessabus`.
The difference can be simply "racing" now the workflow/path is different and it's possible that the push is done in the correct timing. Anyway you should ensure that you complete when all push are done or you could have different race in future.

**Comment by thomhurst** [comment]
> Anyway you should ensure that you complete when all push are done or you could have different race in future.

Yeah I always have been completing after awaiting everything possible. This is the commit that seemed to fix everything. No changes to any waiting or async calls, just simply switching out one message bus object, to the context object: https://github.com/thomhurst/TUnit/commit/ac7a2f1e0181fafed0d9a7d5b44067af86f7856f

**Comment by MarcoRossignoli** [comment]
Going to close for now, doesn't look an issue on TA side.

**Comment by Evangelink** [comment]
@thomhurst Please while you are implementing your test framework keep creating issues everytime something is unclear/confusing or anything. You are our first external user of a new framework so your input is invaluable to us.

**Pull request closed without merging**
