### PR TITLE
Replace Usings.cs with <Using> in SDK samples

### PR DESCRIPTION
**Pull request by nohwnd**
Fix https://github.com/microsoft/testfx/issues/3069

### CODE REVIEW

**Comment by cremor** [comment]
(Answering your comment in the issue) Yes, that's what I meant, thanks.

But there are more samples in the 3.4 branch, see https://github.com/microsoft/testfx/tree/rel/3.4/samples/public/DemoMSTestSdk
Those additional samples are also linked in the latest blog post. Is it by design that those are not in the main branch?

**Comment by nohwnd** [comment]
I doubt it, @evangelink was finishing his blogpost, and probably forgot to backport to main.

**Comment by cremor** [comment]
Then it would maybe be a good idea to target the 3.4 branch with this PR, change all samples and only then merge it back to main?

**Comment by nohwnd** [comment]
retargeted, the subsequent PR will have to checkout the whole samples/public folder from here, rather than cherry-picking just the final comment. Or take all the relevant commits to samples folder.

**Pull request merged**
