### PR TITLE
remove ServerModeManagerExtensions

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Review by Evangelink — COMMENTED** [review]
@MarcoRossignoli is it used somewhere else (externally)?

**Comment by SimonCropp** [comment]
how can it be used externally if it is internal?

**Comment by Evangelink** [comment]
> how can it be used externally if it is internal?

The wonders of `InternalsVisibleTo`!

**Review by MarcoRossignoli — APPROVED** [review]
It's fine they're helpers that we wanted to ship in future but we can cleanup for now.

**Pull request merged**
