### PR TITLE
Issue when custom test class attribute inherits from TestClassAttribute

### PR DESCRIPTION
**Pull request by parrainc**
This PR fixes issue #503 

By changing the IsAttributeDefined method in the ReflectHelper to look at the memberInfo attributes base type to verify it matches with the attributeType (TestClassAttribute).

Behavior after this fix:

> Call to AssemblyInitialize
> Call to ClassInitialize
> Call to TestMethod(s)
> ...
> Call to ClassCleanup
> Call to AssemblyCleanup

after

### CODE REVIEW

**Comment by parrainc** [comment]
@jayaranigarg can you please see why the Debug/Release build triggers are still pending?

**Comment by mayankbansal018** [comment]
@dotnet-bot test this please

**Comment by mayankbansal018** [comment]
@dotnet-bot test Windows / Debug Build  please

**Comment by jayaranigarg** [comment]
@parrainc : Consider using `inherit` parameter of `IsAttributeDefined()`. Setting this to `true` should work as well.

**Comment by parrainc** [comment]
> @parrainc : Consider using `inherit` parameter of `IsAttributeDefined()`. Setting this to `true` should work as well.

Hi @jayaranigarg if i just set inherit to `true` in line 428, the `IsAttributeDefined()` method wouldn't be reached out with a custom test class attribute. The problem is happening in [line 393](https://github.com/Microsoft/testfx/blob/master/src/Adapter/MSTest.CoreAdapter/Execution/TypeCache.cs#L393) when checking if `IsAttributeDefined()` on the `type` (even with `inherit`set to `true`) the method is not finding a match of `TestClassAttribute` in the type's attributes, hence the test class is not being examined to look for assembly initialize/cleanup methods. 

So, my change in the method, makes sure (as a last resource) to look for a match of the desired `attributeType` in the attributes' BaseType.

**Comment by parrainc** [comment]
@jayaranigarg having that additional check doesn't let the initialize/cleanup method to be discovered. Still happening same issue, around 7 tests failed if line 393 looks like 

```
if (!this.reflectionHelper.IsAttributeDefined(t, typeof(TestClassAttribute), inherit: true)
 || !this.reflectionHelper.HasAttributeDerivedFrom(t, typeof(TestClassAttribute), false))
{ continue; }
```
However, even though the `.HasAttributeDerivedFrom()` would return true in [line 393](https://github.com/Microsoft/testfx/blob/master/src/Adapter/MSTest.CoreAdapter/Execution/TypeCache.cs#L393), when reaching the `.IsAssemblyOrClassInitializeMethod()` in [line 412](https://github.com/Microsoft/testfx/blob/master/src/Adapter/MSTest.CoreAdapter/Execution/TypeCache.cs#L412) or `.IsAssemblyOrClassCleanupMethod()` in line [416](https://github.com/Microsoft/testfx/blob/master/src/Adapter/MSTest.CoreAdapter/Execution/TypeCache.cs#L416), those method would return false and the property `AssemblyInitializeMethod`/`AssemblyCleanupMethod ` wouldn't cached the method, because the `IsAttributeDefined` method in [line 32](https://github.com/Microsoft/testfx/blob/master/src/Adapter/MSTest.CoreAdapter/Helpers/ReflectHelper.cs#L32) from ReflectHelper is looking for the attributes of the test class, and won't match with `TestClassAttribute` but `DummyTestClassAttribute`.

Please, review and advise.

**Comment by jayaranigarg** [comment]
@parrainc : It seems to work fine for me. Refer this PR : https://github.com/Microsoft/testfx/pull/525

**Comment by parrainc** [comment]
> @parrainc : It seems to work fine for me. Refer this PR : #525

You're correct, I was using OR comparator instead of AND.
Updated myself and seems to work fine.

Should I close this PR and you go ahead and merge #525 ?

**Comment by jayaranigarg** [comment]
@parrainc : Thank you for the contribution. Release build is failing on this PR for some reason. I guess we will just take the other PR.

**Pull request closed without merging**
