### PR TITLE
move to file scoped namespaces

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Review by Evangelink — COMMENTED** [review]
Hi @SimonCropp, 

Are you seeing issues when compiling the analyzers and code-fixes projects? I have disabled most of the rules we use in our repo on the `RoslynAnalyzerHelpers` folder to make it easier for me to diff if there is any change in these helpers that I simply copy-pasted from `dotnet/roslyn-analyzers`.

The namespace change doesn't bother me more than that but I am wondering if it would impact negatively our experience of reflecting changes. I am not sure... Will be thinking about it and let you know.

**Comment by SimonCropp** [comment]
> Are you seeing issues when compiling the analyzers and code-fixes projects

nope

what are you seeing?

**Comment by Evangelink** [comment]
I don't have issues, I was wondering the reasons for these changes. As I said, I am/was trying to make it easier to diff the files from roslyn-analyzers repo hence the difference in style and the set of disabled analyzers for these folders.

I don't know if that's really a good idea or not.

**Comment by SimonCropp** [comment]
i was just making the approach to namespaces consistent. happy to close if u dont like the idea

**Comment by SimonCropp** [comment]
but yeah. let kill it

**Pull request closed without merging**
