### PR TITLE
Upgrade VSSDK

### PR DESCRIPTION
**Pull request by singhsarab**
Upgrading the version of VSSDK Build tools nuget, because the older one is incompatible with the latest VSSDK.

### CODE REVIEW

**Comment by jayaranigarg** [comment]
Awesome 👍

**Comment by jayaranigarg** [comment]
Raise a similar one for vstest as well.

**Comment by singhsarab** [comment]
Already did, here is the one for vstest : https://github.com/Microsoft/vstest/pull/1761

**Comment by singhsarab** [comment]
@dotnet-bot test Windows / Debug Build

**Pull request merged**
